apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: search-api-ci-pipeline
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: repo-url
        value: "https://github.com/your-org/search-api"
      - name: branch
        value: "main"
      - name: registry-url
        value: "harbor.your-domain.com"  # or ghcr.io, docker.io, registry.gitlab.com, etc.
      - name: image-ref
        value: "harbor.your-domain.com/search-api/search-api"  # Full image path without tag
      - name: image-tag
        value: "{{workflow.creationTimestamp.Y}}{{workflow.creationTimestamp.m}}{{workflow.creationTimestamp.d}}-{{workflow.uid}}"

  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

  templates:
    - name: main
      steps:
        - - name: checkout
            template: git-clone

        - - name: dagger-pipeline
            template: run-dagger-pipeline

        - - name: notify-success
            template: notify
            arguments:
              parameters:
                - name: status
                  value: "SUCCESS"

    - name: git-clone
      inputs:
        parameters:
          - name: repo-url
            value: "{{workflow.parameters.repo-url}}"
          - name: branch
            value: "{{workflow.parameters.branch}}"
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |
            git clone --depth 1 --branch {{inputs.parameters.branch}} {{inputs.parameters.repo-url}} /work/source
        volumeMounts:
          - name: work
            mountPath: /work

    - name: run-dagger-pipeline
      inputs:
        parameters:
          - name: registry-url
            value: "{{workflow.parameters.registry-url}}"
          - name: image-ref
            value: "{{workflow.parameters.image-ref}}"
          - name: image-tag
            value: "{{workflow.parameters.image-tag}}"
      container:
        image: registry.dagger.io/engine:v0.9.5
        command: [sh, -c]
        args:
          - |
            cd /work/source

            # Run the full Dagger pipeline with registry push
            dagger call full-pipeline \
              --source=. \
              --registry-url={{inputs.parameters.registry-url}} \
              --registry-username=env:REGISTRY_USERNAME \
              --registry-password=env:REGISTRY_PASSWORD \
              --image-ref={{inputs.parameters.image-ref}} \
              --tag={{inputs.parameters.image-tag}}
        env:
          - name: REGISTRY_USERNAME
            valueFrom:
              secretKeyRef:
                name: registry-credentials
                key: username
          - name: REGISTRY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: registry-credentials
                key: password
          - name: _EXPERIMENTAL_DAGGER_RUNNER_HOST
            value: "unix:///var/run/buildkit/buildkitd.sock"
        volumeMounts:
          - name: work
            mountPath: /work
          - name: dagger-socket
            mountPath: /var/run/buildkit
        securityContext:
          privileged: true

    - name: notify
      inputs:
        parameters:
          - name: status
      container:
        image: curlimages/curl:latest
        command: [sh, -c]
        args:
          - |
            # Send notification (example with webhook)
            curl -X POST $WEBHOOK_URL \
              -H "Content-Type: application/json" \
              -d '{
                "status": "{{inputs.parameters.status}}",
                "workflow": "{{workflow.name}}",
                "image_tag": "{{workflow.parameters.image-tag}}"
              }'
        env:
          - name: WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: webhook-config
                key: url
                optional: true

  onExit: cleanup

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: argo
type: Opaque
stringData:
  username: "admin"  # Registry username (Harbor, GHCR, Docker Hub, etc.)
  password: "CHANGE_ME"  # Registry password or personal access token
  # In production, use Infisical or external secrets operator:
  # apiVersion: external-secrets.io/v1beta1
  # kind: ExternalSecret
  # metadata:
  #   name: registry-credentials
  # spec:
  #   refreshInterval: 1h
  #   secretStoreRef:
  #     name: infisical-secret-store
  #     kind: SecretStore
  #   target:
  #     name: registry-credentials
  #   data:
  #     - secretKey: username
  #       remoteRef:
  #         key: registry-username
  #     - secretKey: password
  #       remoteRef:
  #         key: registry-password
